[2022-12-13 15:27:43,838] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_tripdata1_dag.bigquery_external_table_task manual__2022-12-12T15:20:27.855458+00:00 [queued]>
[2022-12-13 15:27:43,876] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_tripdata1_dag.bigquery_external_table_task manual__2022-12-12T15:20:27.855458+00:00 [queued]>
[2022-12-13 15:27:43,876] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 15:27:43,876] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-12-13 15:27:43,876] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 15:27:43,915] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2022-12-12 15:20:27.855458+00:00
[2022-12-13 15:27:43,929] {standard_task_runner.py:52} INFO - Started process 20453 to run task
[2022-12-13 15:27:43,951] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_tripdata1_dag', 'bigquery_external_table_task', 'manual__2022-12-12T15:20:27.855458+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_tripdata1_dag.py', '--cfg-path', '/tmp/tmp0lzp5a21', '--error-file', '/tmp/tmp7ju1xqrv']
[2022-12-13 15:27:43,957] {standard_task_runner.py:77} INFO - Job 199: Subtask bigquery_external_table_task
[2022-12-13 15:27:44,182] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_tripdata1_dag.bigquery_external_table_task manual__2022-12-12T15:20:27.855458+00:00 [running]> on host c90fde5b5e35
[2022-12-13 15:27:44,361] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_tripdata1_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T15:20:27.855458+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T15:20:27.855458+00:00
[2022-12-13 15:27:44,363] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-12-13 15:27:44,782] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/weighty-diorama-365805/datasets/session6/tables?prettyPrint=false: Error while reading table: answer1, error message: Input file is not in Parquet format. File: gs://data-fellowship08-nyoba/raw/part-00000-64ea0de6-d39a-42f0-9ba5-2200d99d66d6-c000.snappy.parquet
[2022-12-13 15:27:44,824] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_tripdata1_dag, task_id=bigquery_external_table_task, execution_date=20221212T152027, start_date=20221213T152743, end_date=20221213T152744
[2022-12-13 15:27:44,876] {standard_task_runner.py:92} ERROR - Failed to execute job 199 for task bigquery_external_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/weighty-diorama-365805/datasets/session6/tables?prettyPrint=false: Error while reading table: answer1, error message: Input file is not in Parquet format. File: gs://data-fellowship08-nyoba/raw/part-00000-64ea0de6-d39a-42f0-9ba5-2200d99d66d6-c000.snappy.parquet
[2022-12-13 15:27:44,910] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-12-13 15:27:45,005] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
