[2022-12-05 07:59:44,960] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.getData scheduled__2022-12-04T00:00:00+00:00 [queued]>
[2022-12-05 07:59:44,979] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.getData scheduled__2022-12-04T00:00:00+00:00 [queued]>
[2022-12-05 07:59:44,980] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-12-05 07:59:44,980] {taskinstance.py:1239} INFO - Starting attempt 11 of 12
[2022-12-05 07:59:44,980] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-12-05 07:59:45,009] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): getData> on 2022-12-04 00:00:00+00:00
[2022-12-05 07:59:45,019] {standard_task_runner.py:52} INFO - Started process 298 to run task
[2022-12-05 07:59:45,029] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'getData', 'scheduled__2022-12-04T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp70egpwkp', '--error-file', '/tmp/tmpmpdzuwl2']
[2022-12-05 07:59:45,031] {standard_task_runner.py:77} INFO - Job 122: Subtask getData
[2022-12-05 07:59:45,115] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.getData scheduled__2022-12-04T00:00:00+00:00 [running]> on host 53cedc9262d0
[2022-12-05 07:59:45,183] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=getData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-04T00:00:00+00:00
[2022-12-05 07:59:45,335] {python.py:175} INFO - Done. Returned value was: None
[2022-12-05 07:59:45,356] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=getData, execution_date=20221204T000000, start_date=20221205T075944, end_date=20221205T075945
[2022-12-05 07:59:45,414] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-12-05 07:59:45,476] {dagrun.py:628} WARNING - Failed to get task '<TaskInstance: data_ingestion_gcs_dag.get_data_task scheduled__2022-12-04T00:00:00+00:00 [removed]>' for dag 'data_ingestion_gcs_dag'. Marking it as removed.
[2022-12-05 07:59:45,497] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
